apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-demo
  template:
    metadata:
      labels:
        app: gke-demo
    spec:
      containers:
      - name: gke-demo
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
